/* Generate Yandl/words.js — the bundled dictionary.
 *
 *  ANSWERS  : common 5-letter words (the daily-solution pool), sourced from
 *             google-10000-english (public domain / MIT). Stable pseudo-random
 *             order so consecutive days aren't alphabetically adjacent.
 *  ALLOWED  : every accepted guess = ANSWERS ∪ all 5-letter words from
 *             an-array-of-english-words (MIT). Stored as one concatenated
 *             5-char-per-word blob to keep the file small.
 *
 *  Run: npm run words   (regenerating changes nothing at runtime unless you
 *  commit the new words.js; the daily sequence is stable for a fixed word set).
 */
import { readFile, writeFile } from 'node:fs/promises';

const FIVE = /^[a-z]{5}$/;

// ── ALLOWED: broad English dictionary (also our proper-noun filter) ──
const bigJson = await readFile('node_modules/an-array-of-english-words/index.json', 'utf8');
const big = JSON.parse(bigJson);
const allowedSet = new Set(big.filter((w) => FIVE.test(w)));

// ── ANSWERS: common words ────────────────────────────────────────────
const COMMON_URL =
  'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa-no-swears.txt';
const commonTxt = await (await fetch(COMMON_URL)).text();
// Proper nouns, brand/tech tokens, slang and abbreviations that survive the
// dictionary filter but make poor (unfair / off-brand) daily answers. They
// remain valid *guesses* (still in ALLOWED) — just never the word of the day.
const BLOCK = new Set([
  // people / names
  'barry','betty','billy','bobby','burke','cohen','colin','craig','danny','devon',
  'diane','donna','harry','henry','james','jenny','jerry','jesse','jesus','jimmy',
  'johns','jones','kelly','kerry','laura','lewis','logan','louis','maria','moses',
  'nancy','oscar','perry','peter','ralph','randy','roger','sally','smith','teddy',
  'terry','tommy','tyler',
  // places / nationalities
  'chile','china','congo','costa','dover','india','japan','leone','niger','paris',
  'spain','texas','vegas','wales','welsh',
  // brands / tech / abbreviations / slang
  'adobe','cisco','chevy','ebook','emacs','honda','intel','linux','xerox','yahoo',
  'devel','diffs','admin','debug','login','inbox','blogs','gonna','gotta','wanna',
  'kinda','whats',
]);

// Intersect common words with the real dictionary so proper nouns and non-words
// can't be daily answers, then drop the blocklist.
const answers = [...new Set(commonTxt.split(/\s+/).filter((w) => FIVE.test(w)))]
  .filter((w) => allowedSet.has(w) && !BLOCK.has(w));

// ── Stable pseudo-random ordering for the daily sequence ─────────────
// FNV-1a hash → deterministic, so the same word set always yields the
// same order (and therefore the same word on a given date).
function hash(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}
answers.sort((a, b) => hash(a) - hash(b) || (a < b ? -1 : 1));

// ALLOWED blob (sorted for stable diffs); answers excluded to avoid dupes.
const allowedOnly = [...allowedSet].filter((w) => !answers.includes(w)).sort();
const blob = allowedOnly.join('');

const file = `// AUTO-GENERATED by scripts/gen-words.mjs — do not edit by hand.
// ANSWERS: ${answers.length} common words (daily pool) · ALLOWED total: ${allowedSet.size}
window.YandlWords = (function () {
  var ANSWERS = ${JSON.stringify(answers)};
  // every other valid 5-letter guess, concatenated 5 chars per word
  var BLOB = ${JSON.stringify(blob)};
  var allowed = new Set(ANSWERS);
  for (var i = 0; i < BLOB.length; i += 5) allowed.add(BLOB.slice(i, i + 5));
  return {
    ANSWERS: ANSWERS,
    isAllowed: function (w) { return allowed.has(String(w || '').toLowerCase()); },
    size: allowed.size
  };
})();
`;

await writeFile('Yandl/words.js', file);
console.log(
  `wrote Yandl/words.js — ANSWERS ${answers.length}, ALLOWED ${allowedSet.size}, ~${Math.round(file.length / 1024)}KB raw`
);
